### PR TITLE
Rename mobile_default_theme functionality to default_theme

### PR DESCRIPTION
**Pull request by fredj**
The value will now be used ba the desktop and mobile interfaces

### CODE REVIEW

**Comment by sbrunner** [comment]
By the way you can also add it here: https://github.com/camptocamp/c2cgeoportal/blob/9544013afc7f68033099fc92f812137d0fe979df/c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl#L195

**Comment by fredj** [comment]
@sbrunner you're right, added

**Comment by sbrunner** [comment]
Looks good, merge, when it's OK for Travis :-)

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
