### PR TITLE
Add floors configuration

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
I feel wreid to see those values in a CONST file in scaffold, here is custom config for demo_geomapfish.

**Comment by arnaud-morvan** [comment]
Maybe having a list of 3 values here would do the job as default value for everyone.

**Comment by sbrunner** [comment]
> I feel wreid to see those values in a CONST file in scaffold, here is custom config for demo_geomapfish.

In the past I do the choice to make it available for everyone, I don't know if it's good or not, If we want we can change it for 2.5...

**Comment by sbrunner** [comment]
> Maybe having a list of 3 values here would do the job as default value for everyone.

+1 :-)

**Pull request merged**
