### PR TITLE
Add missing Alembic merge.

### PR DESCRIPTION
**Pull request by pvalsecc**

### CODE REVIEW

**Comment by ochriste** [comment]
+1

**Comment by sbrunner** [comment]
-1 missing branch label :-(

**Comment by ochriste** [comment]
there is none there too : https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/1418cb05921b_merge_1_6_and_master_branches.py

**Comment by ochriste** [comment]
what are the labels for ?

**Pull request closed without merging**
