### PR TITLE
Set src for external ngeo component

### PR DESCRIPTION
**Pull request by ger-benjamin**
Fix: https://github.com/camptocamp/c2cgeoportal/issues/2670

### CODE REVIEW

**Comment by fredj** [comment]
LGTM

**Comment by ger-benjamin** [comment]
What is wrong with travis :confused:  ?

**Comment by fredj** [comment]
> What is wrong with travis :confused:  ?

timeout, I've restarted the build

**Comment by fredj** [comment]
@ger-benjamin travis is green

**Comment by ger-benjamin** [comment]
@fredj Thanks !

**Pull request merged**
