### PR TITLE
Add static Alembic chain, move user on static schema

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by asaunier** [comment]
Commit 5c84500cd4128fae1fc0ef5167a73d6092bcf652 contains a "pyo" file: c2cgeoportal/scaffolds/update/CONST_alembic/env.pyo
Is it really wanted?

**Comment by sbrunner** [comment]
No, thanks ...

**Comment by sbrunner** [comment]
Finally yes, I remove the binary file :-)

**Comment by asaunier** [comment]
No other "objection". OK for me when Travis passes.

**Comment by rbovard** [comment]
@sbrunner Why did you removed the password replication?

**Comment by sbrunner** [comment]
It will be done because we have the user table in main schema and then when we deploy the application we lost the changed password. Now the user table is in the static schema than we don't have anymore this issue and we don't need anymore this functionality.

**Comment by rbovard** [comment]
And for the people who deploy all the DB... ?

**Comment by sbrunner** [comment]
We have two schema to clearly separate the data that are modified on the client application than it's a relay bad idea to deploy all the database ...

And from now isn't a no good ides to deploy all the database, you will lost all the editing layers (that's possible that you haven't) but you also lost your short URL ...

**Comment by rbovard** [comment]
Mmm ok... I know it's not the better way to deploy all the DB but it works. I'll change my procedures, no problems.

Please just don't forget to mention that in changelog for people who using it.

**Comment by sbrunner** [comment]
Effectively :-)

**Pull request merged**
