### PR TITLE
Add a new resourceproxy service, allowing to load external resources.

### PR DESCRIPTION
**Pull request by ochriste**
Useful when the project is configured with https and you want to include non-https content. The resources url host must be specifically added in the project configuration to be allowed to be loaded.

Needed in the Morges project.

### CODE REVIEW

**Comment by sbrunner** [comment]
It relay a security holl, and as it's configured by default it is...

**Comment by ochriste** [comment]
let me know when you have a moment to discuss about this

**Comment by sbrunner** [comment]
Looks good

**Comment by sbrunner** [comment]
up

**Pull request merged**
