### PR TITLE
Script docker-run: fix home directory setting

### PR DESCRIPTION
**Pull request by jwkaltz**
Fix home directory setting in docker-run script, necessary for example when using sigdev with npm

### CODE REVIEW

**Comment by jwkaltz** [comment]
FYI @danduk82 and @ger-benjamin

**Review by ger-benjamin — APPROVED** [review]
Looks good, but we lost flexibility. It is okay to not be able anymore to specify a direction via the `HOME` environment variable ?

**Comment by sbrunner** [comment]
I just see that the line 131 should also be changed ...

**Comment by jwkaltz** [comment]
> I just see that the line 131 should also be changed ...

@sbrunner I changed this as well, now

**Comment by sbrunner** [comment]
@ger-benjamin we steel can use the HOME for the external home directory, this is essentially for the user sigdev where his home is '/var/sigdev' and the '/var' is readonly inside Docker...

**Pull request merged**
