### PR TITLE
All database configuration from the config container got the QGIS plugin

### PR DESCRIPTION
**Pull request by sbrunner**
For less confusion

### CODE REVIEW

**Review by arnaud-morvan — COMMENTED** [review]
Not sure to fully understand.
Where do $ variables comes from ?
Is it just that replacements are done at build time (in config build) and not at run time ?
Note that c2c.template README does not contains any mention of t
his $ variables.

**Comment by sbrunner** [comment]
They are interpreted in the config container as the runtime, with the config container environment variables :-)

**Review by arnaud-morvan — APPROVED** [review]
If I correctly understand, those variables are interpreted by envsubst in config entry point (eval-templates) (this is a .yaml.tmpl_tmpl file :-).

**Comment by sbrunner** [comment]
+1, thanks :-)

**Pull request merged**
