### PR TITLE
Merge 2.2 into 2.3

### PR DESCRIPTION
**Pull request by ger-benjamin**
I had a conflict with this file:
2.2: https://github.com/camptocamp/c2cgeoportal/commit/1d28b290cc5ef106fd972e5fb58ebee3188f3489
2.3: https://github.com/camptocamp/c2cgeoportal/blob/2.3/commons/c2cgeoportal_commons/alembic/main/21f11066f8ec_trigger_on_role_updates_user_in_static.py

It's not in this merge, I think we had to move it / adapt it manually. That's why it's already on 2.3

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
As said in #4118 I think should better creating an alembic merge migration.
Because each one is already in a released version of GMF, so we may have some databases with the two revisions.

**Comment by arnaud-morvan** [comment]
See : https://alembic.zzzcomputing.com/en/latest/branches.html#merging-branches

**Comment by ger-benjamin** [comment]
@arnaud-morvan , so, I can simply remplace the current (2.3) down_revision from:
`down_revision = 'd48a63b348f1'` to `down_revision = ('d48a63b348f1', 'd8ef99bc227e')` ?

**Comment by arnaud-morvan** [comment]
You should not alter the existing migrations as they may already be used (saved in databases), you should create a merge migration.
In some cases, for a migration backport, we may empty the duplicated migration coming from 2.3, but here, it is not necessary as it can run twice.

**Comment by ger-benjamin** [comment]
@arnaud-morvan Thansk again for the precious help !
I've added the missing alembic file in this PR

**Pull request merged**
