### PR TITLE
Fix unworking alternate_projections behivior

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Review by ger-benjamin — APPROVED** [review]
Thanks.

Should we add EPSG:4326 in the list of alternate_projections (was supoorted in 2.5, but EPSG3857 is new)

I can adapt the demo if you want.

**Comment by sbrunner** [comment]
It's already done:
https://github.com/camptocamp/c2cgeoportal/blob/master/geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl#L9-L12
:-)

**Comment by ger-benjamin** [comment]
I see :

```
  alternate_projections: &alternate_projections
    - EPSG:3857
    - EPSG:{srid}
    - EPSG:21781
    
```

But not EPSG:4326

**Comment by ger-benjamin** [comment]
Thanks please merge !

**Pull request merged**
