### PR TITLE
Convert debug print attribute to boolean

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by elemoine** [comment]
Did you mean to change `en.js` and `fr.js` as part of this PR?

**Comment by elemoine** [comment]
Does this change require notes in the changelog file?

**Comment by sbrunner** [comment]
For me no because it's related to the current print configuration...

**Comment by elemoine** [comment]
> For me no because it's related to the current print configuration...

Ok, just wanted to make sure.

How my questions related to the changes to the lang files?

**Comment by sbrunner** [comment]
Not directly , and I see an error ..
I just separate the commit, fix the error, and update the pull request :-)

**Comment by asaunier** [comment]
No objection from my perspective. @elemoine is it OK for you?

**Pull request merged**
