### PR TITLE
User on ngeo interfaces

### PR DESCRIPTION
**Pull request by ger-benjamin**

### CODE REVIEW

**Comment by fredj** [comment]
LGTM

**Comment by sbrunner** [comment]
Why do you need that?

I don't like to add the user, it can brake the cash system, But I think that ok here :-)

**Comment by fredj** [comment]
The gcxp also has the user value

**Comment by ger-benjamin** [comment]
Same needs as in the viewer.js. To do things like https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/create/%2Bpackage%2B/templates/viewer.js_tmpl#L307

But if you have a better idea, it is welcome :-) (that can be temporary, for dev purpose...)

**Comment by sbrunner** [comment]
OK, thanks, merge :-)

**Pull request merged**
