### PR TITLE
Upgrade the python packages versions

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by elemoine** [comment]
LGTM.

**Comment by fredj** [comment]
@sbrunner Pylons was not removed from `CONST_dev-requirements.txt`: is it correct?

**Comment by sbrunner** [comment]
Pylons => Pyramid :-)

the master egg will be removed from CONST_dev-requirements.txt
But the alpha version is added in the CONST_versions.txt : `pyramid==1.6a2`

**Comment by fredj** [comment]
ok, thanks for the explanation

**Pull request merged**
