### PR TITLE
Ignore pull failures in build

### PR DESCRIPTION
**Pull request by arnaud-morvan**
It is not possible to pull config image which is build locally.

### CODE REVIEW

**Comment by sbrunner** [comment]
You have an image that you build with a separate docker build?

**Comment by arnaud-morvan** [comment]
No, it fails on `docker-compose pull`, before `docker-compose build`.

**Comment by arnaud-morvan** [comment]
Note that we do not run `docker-compose pull` in CI

**Comment by sbrunner** [comment]
The `docker-compose pull` in done on the `demo` CI with the `build`...
And I didn't get an error on `docker-compose pull` on service with a `build` section...

**Comment by arnaud-morvan** [comment]
Maybe this depends on docker-compose version.

```
$ ./build --verbose
Use env files: env.default, env.project, env.secrets
docker-compose pull
[+] Running 9/14
 ⠿ alembic Error                                                                                                                                                             2.2s
 ⠿ front Pulled                                                                                                                                                              1.8s
 ⠿ print Pulled                                                                                                                                                              2.2s
 ⠿ config Error                                                                                                                                                              2.2s
 ⠿ redis_slave Pulled                                                                                                                                                        1.8s
 ⠿ tilecloudchain Pulled                                                                                                                                                     1.8s
 ⠿ geoportal Error                                                                                                                                                           2.2s
 ⠿ mapserver Pulled                                                                                                                                                          1.8s
 ⠿ tilegeneration_slave Pulled                                                                                                                                               1.8s
 ⠿ tinyows Error                                                                                                                                                             2.2s
 ⠿ qgisserver Pulled                                                                                                                                                         1.8s
 ⠿ tools Error                                                                                                                                                               2.2s
 ⠿ redis_master Pulled                                                                                                                                                       1.8s
 ⠿ redis_sentinel Pulled                                                                                                                                                     1.8s
WARNING: Some service image(s) must be built from source by running:
    docker compose build alembic config geoportal
Error response from daemon: pull access denied for camptocamp/geomapfishdemo-geoportal, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Traceback (most recent call last):
  File "./build", line 154, in <module>
    main()
  File "./build", line 125, in main
    run(args, ["docker-compose", "pull"], check=True)  # nosec
  File "./build", line 22, in run
    subprocess.run(command, **kwargs)  # nosec
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker-compose', 'pull']' returned non-zero exit status 18.
```

**Comment by sbrunner** [comment]
I don't have the on my host, what's your docker-compose version?
Mine is `1.29.2`

**Comment by arnaud-morvan** [comment]
Docker Compose version v2.2.3

**Comment by sbrunner** [comment]
The last time I use Docker compose v2 I get many issues, it didn't look to be stable :-(

**Comment by arnaud-morvan** [comment]
Ok switched to last v1, no error anymore, closing.

**Pull request closed without merging**
