### PR TITLE
Use Docker Compose version 2.x

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Review by arnaud-morvan — COMMENTED** [review]
Why not using "docker compose"

**Comment by sbrunner** [comment]
Because it imposes to use the v2
If I steal use docker-compose it works on booth cases :-)

**Review by arnaud-morvan — COMMENTED** [review]
Shouldn't we replace it everywhere ?
I would expect we do not need to install docker-compose anymore.

```
$ git grep -n docker-compose
.github/workflows/main.yaml:38:      - run: pip uninstall docker-compose
.github/workflows/main.yaml:91:      - run: docker-compose logs --timestamps
.github/workflows/main.yaml:103:      - run: docker-compose down
.github/workflows/main.yaml:171:      - run: pip uninstall docker-compose
.github/workflows/ngeo-2-6.yaml:56:      - run: docker-compose logs --timestamps
.github/workflows/ngeo-2-6.yaml:60:          ci/run-dc-logs docker-compose exec -T tests pytest --verbose --color=yes --junitxml=/tmp/commons.xml
.github/workflows/ngeo-2-6.yaml:64:          ci/run-dc-logs docker-compose exec -T tests pytest --verbose --color=yes --junitxml=/tmp/geoportal.xml
.github/workflows/ngeo-2-6.yaml:68:          ci/run-dc-logs docker-compose exec -T tests pytest --verbose --color=yes --junitxml=/tmp/admin.xml
.github/workflows/ngeo-2-6.yaml:72:          ci/run-dc-logs docker-compose exec -T qgisserver-tests pytest --verbose --color=yes --junitxml=/tmp/qgis.xml
.github/workflows/ngeo-2-6.yaml:74:      - run: docker-compose down
.github/workflows/ngeo-2-6.yaml:98:          for service in $(docker-compose config --services)
.github/workflows/ngeo-2-6.yaml:100:            docker-compose logs ${service}
.github/workflows/ngeo-2-7.yaml:59:      - run: docker-compose logs --timestamps
.github/workflows/ngeo-2-7.yaml:63:          docker-compose exec -T tests pytest --verbose --color=yes --junitxml=/tmp/commons.xml
.github/workflows/ngeo-2-7.yaml:68:          docker-compose exec -T tests pytest --verbose --color=yes --junitxml=/tmp/geoportal.xml
.github/workflows/ngeo-2-7.yaml:73:          docker-compose exec -T tests pytest --verbose --color=yes --junitxml=/tmp/admin.xml
.github/workflows/ngeo-2-7.yaml:78:          docker-compose exec -T qgisserver-tests pytest --verbose --color=yes --junitxml=/tmp/qgis.xml
.github/workflows/ngeo-2-7.yaml:82:      - run: docker-compose down
.github/workflows/ngeo-2.8.yaml:70:      - run: docker-compose logs --timestamps
.github/workflows/ngeo-2.8.yaml:82:      - run: docker-compose down
.github/workflows/ngeo-2.8.yaml:116:      - run: pip install --user PyYAML==3.13 docker-compose==1.25.0 urllib3==1.26.15
.github/workflows/ngeo-2.8.yaml:145:      - run: pip install --user PyYAML docker-compose wheel
.github/workflows/qgis.yaml:74:          docker-compose up -d
.github/workflows/qgis.yaml:75:          docker-compose exec -T tests /tests/wait-db
.github/workflows/qgis.yaml:76:          docker-compose exec -T tests alembic --config=/tests/alembic.ini --name=main upgrade head
.github/workflows/qgis.yaml:77:          docker-compose exec -T tests alembic --config=/tests/alembic.ini --name=static upgrade head
.github/workflows/qgis.yaml:78:          docker-compose exec -T tests /tests/fill-db
.github/workflows/qgis.yaml:80:          docker-compose exec -T tests /tests/acceptance-tests
.github/workflows/qgis.yaml:83:      - run: docker-compose down
.github/workflows/rebuild-2-6.yaml:66:      - run: docker-compose logs --timestamps
.github/workflows/rebuild-2-6.yaml:70:          ci/run-dc-logs docker-compose exec -T tests
.github/workflows/rebuild-2-6.yaml:75:          ci/run-dc-logs docker-compose exec -T tests
.github/workflows/rebuild-2-6.yaml:80:          ci/run-dc-logs docker-compose exec -T tests
.github/workflows/rebuild-2-6.yaml:85:          ci/run-dc-logs docker-compose exec -T qgisserver-tests
.github/workflows/rebuild-2-6.yaml:88:      - run: docker-compose down
.github/workflows/rebuild-2-6.yaml:112:          for service in $(docker-compose config --services)
.github/workflows/rebuild-2-6.yaml:114:            docker-compose logs ${service}
.github/workflows/rebuild-2-7.yaml:64:      - run: docker-compose logs --timestamps
.github/workflows/rebuild-2-7.yaml:68:          docker-compose exec -T tests coverage run
.github/workflows/rebuild-2-7.yaml:75:          docker-compose exec -T tests coverage run --append
.github/workflows/rebuild-2-7.yaml:82:          docker-compose exec -T tests coverage run --append
.github/workflows/rebuild-2-7.yaml:89:          docker-compose exec -T qgisserver-tests coverage run
.github/workflows/rebuild-2-7.yaml:96:          docker-compose exec -T tests coverage report
.github/workflows/rebuild-2-7.yaml:97:          docker-compose exec -T tests coverage html --directory=/tmp/coverage
.github/workflows/rebuild-2-7.yaml:98:          docker-compose exec -T qgisserver-tests coverage report
.github/workflows/rebuild-2-7.yaml:99:          docker-compose exec -T qgisserver-tests coverage html --directory=/tmp/coverage
.github/workflows/rebuild-2-7.yaml:108:      - run: docker-compose down
.github/workflows/rebuild-2-8.yaml:73:      - run: docker-compose logs --timestamps
.github/workflows/rebuild-2-8.yaml:85:      - run: docker-compose down
.github/workflows/rebuild-2-8.yaml:118:      - run: pip install --user PyYAML==3.13 docker-compose==1.26.0 urllib3==1.26.15
.github/workflows/rebuild-2-8.yaml:135:      - run: pip install --user PyYAML==5.3.1 docker-compose==1.29.2 wheel==0.40.0 urllib3==1.26.15
.github/workflows/rebuild-qgis-2-6.yaml:64:          docker-compose up -d
.github/workflows/rebuild-qgis-2-6.yaml:65:          docker-compose exec -T tests /tests/wait-db
.github/workflows/rebuild-qgis-2-6.yaml:66:          docker-compose exec -T tests alembic --config=/tests/alembic.ini --name=main upgrade head
.github/workflows/rebuild-qgis-2-6.yaml:67:          docker-compose exec -T tests alembic --config=/tests/alembic.ini --name=static upgrade head
.github/workflows/rebuild-qgis-2-6.yaml:68:          docker-compose exec -T tests /tests/fill-db
.github/workflows/rebuild-qgis-2-6.yaml:69:          ../../ci/run-dc-logs docker-compose exec -T tests /tests/acceptance-tests
.github/workflows/rebuild-qgis-2-6.yaml:70:          docker-compose down
.github/workflows/rebuild-qgis-2-7.yaml:66:          docker-compose up -d
.github/workflows/rebuild-qgis-2-7.yaml:67:          docker-compose exec -T tests /tests/wait-db
.github/workflows/rebuild-qgis-2-7.yaml:68:          docker-compose exec -T tests alembic --config=/tests/alembic.ini --name=main upgrade head
.github/workflows/rebuild-qgis-2-7.yaml:69:          docker-compose exec -T tests alembic --config=/tests/alembic.ini --name=static upgrade head
.github/workflows/rebuild-qgis-2-7.yaml:70:          docker-compose exec -T tests /tests/fill-db
.github/workflows/rebuild-qgis-2-7.yaml:72:          docker-compose exec -T tests /tests/acceptance-tests
.github/workflows/rebuild-qgis-2-7.yaml:75:      - run: docker-compose down
.github/workflows/rebuild-qgis-2.8.yaml:68:          docker-compose up -d
.github/workflows/rebuild-qgis-2.8.yaml:69:          docker-compose exec -T tests /tests/wait-db
.github/workflows/rebuild-qgis-2.8.yaml:70:          docker-compose exec -T tests alembic --config=/tests/alembic.ini --name=main upgrade head
.github/workflows/rebuild-qgis-2.8.yaml:71:          docker-compose exec -T tests alembic --config=/tests/alembic.ini --name=static upgrade head
.github/workflows/rebuild-qgis-2.8.yaml:72:          docker-compose exec -T tests /tests/fill-db
.github/workflows/rebuild-qgis-2.8.yaml:74:          docker-compose exec -T tests /tests/acceptance-tests
.github/workflows/rebuild-qgis-2.8.yaml:77:      - run: docker-compose down
Makefile:110:	docker-compose exec -T tests pytest --verbose --color=yes \
Makefile:115:	docker-compose exec -T tests pytest --verbose --color=yes \
Makefile:120:	docker-compose exec -T tests pytest --verbose --color=yes \
Makefile:125:	docker-compose exec -T qgisserver-tests pytest --verbose --color=yes \
Makefile:131:	docker-compose up -d
Makefile:132:	docker-compose exec -T tests wait-db
Makefile:133:	docker-compose exec -T tests alembic --config=/opt/c2cgeoportal/commons/alembic.ini --name=main \
Makefile:135:	docker-compose exec -T tests alembic --config=/opt/c2cgeoportal/commons/alembic.ini --name=static \
Makefile:137:	docker-compose exec -T tests psql --command='DELETE FROM main_static.user_role'
Makefile:138:	docker-compose exec -T tests psql --command='DELETE FROM main_static."user"'
Makefile:142:	docker-compose stop --timeout=0
Makefile:143:	docker-compose down --remove-orphans
admin/Makefile:20:	docker-compose up -d db
admin/Makefile:21:	docker-compose run --rm admin wait-db
admin/Makefile:22:	docker-compose run --rm admin alembic --config=/opt/c2cgeoportal/commons/alembic.ini --name=main upgrade head
admin/Makefile:23:	docker-compose run --rm admin alembic --config=/opt/c2cgeoportal/commons/alembic.ini --name=static upgrade head
admin/Makefile:27:	docker-compose up admin
admin/Makefile:31:	docker-compose down --remove-orphans
bin/update-po:25:# Used when we update the po files in the application running in a docker-compose locally.
ci/create-new-project:52:sed -i 's/service: geoportal/\0-advance/g' docker-compose.yaml
ci/create-new-project:53:sed -i 's/service: alembic/\0-advance/g' docker-compose.yaml
ci/docker-compose.override.yaml:16:      file: docker-compose-lib.yaml
ci/docker-compose.override.yaml:32:      file: docker-compose-lib.yaml
ci/docker-compose.override.yaml:42:      file: docker-compose-lib.yaml
ci/requirements-project.txt:4:docker-compose==1.25.0
ci/test-app:8:cp ci/docker-compose.override.yaml "${HOME}/workspace/testgeomapfishapp/"
ci/test-app:37:docker-compose run --entrypoint= --no-deps --rm --volume="$(pwd)/geoportal:/app" geoportal \
ci/test-app:40:docker-compose run --entrypoint= --no-deps --rm --volume="$(pwd)/geoportal:/app" geoportal \
ci/test-app:43:docker-compose run --entrypoint= --no-deps --rm --volume="$(pwd)/geoportal:/app" geoportal \
ci/test-app:46:docker-compose down --volumes
ci/test-app:51:docker-compose up -d
ci/test-app:52:docker-compose exec -T geoportal bash -c 'PGHOST=externaldb PGDATABASE=test wait-db;'
ci/test-app:53:docker-compose exec -T geoportal wait-db
ci/test-app:59:docker-compose exec -T geoportal alembic --config=alembic.ini --name=main upgrade head
ci/test-app:60:docker-compose exec -T geoportal alembic --config=alembic.ini --name=static upgrade head
ci/test-app:61:docker-compose start alembic
ci/test-app:67:docker-compose exec -T geoportal create-demo-theme
ci/test-app:73:docker-compose exec -T geoportal theme2fts
ci/test-app:84:    docker-compose exec -T geoportal curl --fail --insecure "${url}" \
ci/test-app:85:        || (docker-compose exec -T geoportal curl --insecure "${url}" && false)
ci/test-app:91:docker-compose exec -T geoportal proutes c2c://development.ini
ci/test-app:94:docker-compose exec -T geoportal pviews c2c://development.ini /
ci/test-app:97:docker-compose exec -T geoportal proutes c2c://production.ini
ci/test-app:100:docker-compose exec -T geoportal pviews c2c://production.ini /
ci/test-app:113:docker-compose exec -T tools psql --command="ALTER SCHEMA main RENAME TO main_old"
ci/test-app:114:docker-compose exec -T tools psql --command="CREATE SCHEMA main"
ci/test-app:120:docker-compose exec -T geoportal alembic --config=alembic.ini --name=static downgrade base
ci/test-app:121:docker-compose exec -T geoportal alembic --config=alembic.ini --name=main downgrade base
ci/test-app:126:docker-compose exec -T tools rm /etc/mapserver/demo.map
ci/test-app:127:docker-compose exec -T tools mappyfile validate --version=7.6 /etc/mapserver/*.map
ci/test-app:133:docker-compose down
ci/test-app:134:mv docker-compose.override.yaml docker-compose.test.yaml
ci/test-app:139:docker-compose \
ci/test-app:140:    --file=docker-compose.yaml \
ci/test-app:141:    --file=docker-compose-db.yaml \
ci/test-app:142:    --file=docker-compose.test.yaml up -d
ci/test-app:152:docker-compose \
ci/test-app:153:    --file=docker-compose.yaml \
ci/test-app:154:    --file=docker-compose-db.yaml \
ci/test-app:155:    --file=docker-compose.test.yaml \
ci/test-app:156:    --file=docker-compose.override.sample.yaml up -d
ci/test-app:163:docker-compose down --remove-orphans || true
doc/administrator/mapfile.rst:428:   docker-compose exec tools mappyfile validate --version=7.6 /etc/mapserver/*.map
doc/developer/custom_alembic.rst:26:  docker-compose exec geoportal mkdir /tmp/new_alembic
doc/developer/custom_alembic.rst:27:  docker-compose exec geoportal bash -c "cd /tmp/new_alembic; alembic init alembic"
doc/developer/custom_alembic.rst:29:  docker-compose exec geoportal bash -c "cd /tmp/new_alembic; alembic revision -m 'Inital revision'"
doc/developer/custom_alembic.rst:31:Run ``docker-compose ps geoportal`` to know the name of the running geoportal container.
doc/developer/custom_alembic.rst:89:Once your revision file completed, build and run docker-compose up on your project.
doc/developer/custom_alembic.rst:94:  docker-compose exec geoportal bash -c "cd /app/alembic_${PROJECT}; alembic upgrade head"
doc/developer/custom_alembic.rst:103:  docker-compose exec geoportal bash -c "cd /app/alembic_${PROJECT}; alembic revision -m '<msg>'"
doc/developer/debugging.rst:8:First, you should copy the file ``docker-compose.override.sample.yaml`` to
doc/developer/debugging.rst:9:``docker-compose.override.yaml``, and update the composition ``docker-compose up -d``.
doc/developer/debugging.rst:36:``docker-compose.override.yaml`` file.
doc/developer/debugging.rst:46:With the default ``docker-compose.override.yaml``, the debug toolbar should appear.
doc/developer/debugging.rst:60:With the default configuration in the file ``docker-compose.override.yaml``, your application will be
doc/developer/debugging.rst:68:``docker-compose.override.yaml``:
doc/developer/debugging.rst:87:    docker-compose exec mapserver shp2img -m /etc/mapserver/mapserver.map -o /tmp/test.png \
doc/developer/debugging.rst:106:   docker-compose logs -f --tail=20 [<service_name>]
doc/developer/debugging.rst:118:   docker-compose exec [--user=root] <service_name> bash
doc/developer/debugging.rst:128:  ``.env`` or option ``-p`` of ``docker-compose``)
doc/developer/debugging.rst:137:Create a development docker-compose.override.yaml
doc/developer/debugging.rst:140:Be sure that the volume for the project is not commented out in ``docker-compose.override.yaml``.
doc/developer/debugging.rst:142:With the ``docker-compose.override.yaml`` configuration, Gunicorn will automatically restart
doc/developer/debugging.rst:156:If it is not already done, copy the file ``docker-compose.override.sample.yaml`` to
doc/developer/debugging.rst:157:``docker-compose.override.yaml``.
doc/developer/debugging.rst:246:   docker-compose exec tools curl "http://mapserver:8080?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities"
doc/developer/debugging.rst:249:``docker-compose.yaml``, e.g.:
doc/developer/server_side.rst:47:tests require to run with ``docker-compose``.
doc/developer/server_side.rst:68:    docker-compose exec tests pytest --verbose --color=yes \
doc/developer/server_side.rst:125:    docker-compose exec geoportal upgrade head
doc/integrator/authentication.rst:141:   :prog: docker-compose exec geoportal manage-users
doc/integrator/backend_qgis.rst:135:And in your ``docker-compose.yaml`` file:
doc/integrator/build.rst:152:In the build script, we use `docker-compose build`, as this simplifies adding a new service from another `Dockerfile`.
doc/integrator/build.rst:154:By adding the following in the `docker-compose.yaml` file:
doc/integrator/create_application.rst:147:In the ``docker-compose.yaml`` file in the service ``geoportal`` you should replace
doc/integrator/create_application.rst:291:      docker-compose exec geoportal create-demo-theme
doc/integrator/database.rst:66:   docker-compose exec tools psql --file=/opt/clone_schema.sql
doc/integrator/docker.rst:132:* ``docker-compose.yaml``: The main file that describes the composition.
doc/integrator/docker.rst:133:* ``docker-compose-lib.yaml``: Provideis the base description of Geomapfish Docker services.
doc/integrator/docker.rst:135:* ``docker-compose.override[.sample].yaml``: Some rules for debuggung.
doc/integrator/docker.rst:144:   docker-compose up -d
doc/integrator/extend_application.rst:9:- add a custom docker-compose service
doc/integrator/extend_application.rst:63:Add the following service in the ``docker-compose.yaml``, with that we will be able to build and run the image:
doc/integrator/extend_application.rst:86:Add the following service in the ``docker-compose.override.sample.yaml``, To be able to run the service
doc/integrator/extend_application.rst:336:Rename the ``docker-compose.override.sample.yaml`` file to ``docker-compose.override.yaml``.
doc/integrator/extend_application.rst:381:In the ``docker-compose.yaml`` file do the following changes:
doc/integrator/extend_application.rst:387:           file: docker-compose-lib.yaml
doc/integrator/extend_data_model.rst:301:   docker-compose up -d
doc/integrator/extend_data_model.rst:309:   docker-compose exec geoportal python3
doc/integrator/extend_data_model.rst:329:   docker-compose exec tools psql
doc/integrator/fulltext_search.rst:83:   :prog: docker-compose exec geoportal theme2fts
doc/integrator/install_application.rst:111:    cp docker-compose.override.sample.yaml docker-compose.override.yaml
doc/integrator/install_application.rst:117:    docker-compose up -d
doc/integrator/install_application.rst:123:    docker-compose exec geoportal alembic --config=alembic.ini \
doc/integrator/install_application.rst:125:    docker-compose exec geoportal alembic --config=alembic.ini \
doc/integrator/objectstorage.rst:57:   docker-compose exec geoportal bash -c \
doc/integrator/objectstorage.rst:67:   docker-compose exec geoportal azure --list-container
doc/integrator/objectstorage.rst:73:   docker-compose exec geoportal azure --container=<container> --list ''
doc/integrator/objectstorage.rst:79:   docker-compose exec geoportal azure --container=<container> --vrt <folder>/ .tiff
doc/integrator/objectstorage.rst:91:   docker-compose exec geoportal bash -c \
doc/integrator/objectstorage.rst:108:   docker-compose exec geoportal rm index.shp
doc/integrator/objectstorage.rst:109:   docker-compose exec geoportal rm index.shx
doc/integrator/objectstorage.rst:110:   docker-compose exec geoportal rm index.dbf
doc/integrator/objectstorage.rst:111:   docker-compose exec geoportal rm index.prj
doc/integrator/objectstorage.rst:112:   docker-compose exec geoportal bash -c \
doc/integrator/objectstorage.rst:228:Azure docker-compose:
doc/integrator/print.rst:59:To test the print locally, you can copy the ``docker-compose.override.sample.yaml`` to
doc/integrator/print.rst:60:``docker-compose.override.yaml``, and uncomment the ``PRINT_URL`` environment variable and the
doc/integrator/print.rst:69:* Uncomment the ``print`` service in the ``docker-compose.yaml`` file.
doc/integrator/requirements.rst:20:* ``docker-compose>=1.25.0``
doc/integrator/requirements.rst:26:   python3 -m pip install --user PyYAML docker-compose
doc/integrator/security.rst:26:we are on docker-compose we have to choose ourself. The best is to build the image only on
doc/integrator/tilegeneration.rst:70:     docker-compose exec tilecloudchain generate-tiles \
doc/integrator/tilegeneration.rst:95:    docker-compose exec tilecloudchain generate-tiles --help
doc/integrator/tilegeneration.rst:101:    docker-compose exec tilecloudchain generate_controller --help
doc/integrator/tilegeneration.rst:107:    docker-compose exec tilecloudchain generate_controller --cost
doc/integrator/tilegeneration.rst:113:    docker-compose exec tilecloudchain generate-tiles
doc/integrator/upgrade_application.rst:68:   docker-compose exec geoportal alembic --help
doc/integrator/upgrade_application.rst:74:   docker-compose exec geoportal alembic --name=main upgrade head
doc/integrator/upgrade_application.rst:80:   docker-compose exec geoportal alembic --name=static upgrade head
doc/integrator/urllogin.rst:17:To generate a key, you can use the ``docker-compose exec geoportal urllogin`` command:
doc/integrator/urllogin.rst:21:   :prog: docker-compose exec geoportal urllogin
doc/integrator/urllogin.rst:28:You can change the session timeout in the ``docker-compose.yaml`` file with:
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/.gitignore:6:/docker-compose.override.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile:19:	docker-compose run --rm -T tools update-po-only `id --user` `id --group` $(LANGUAGES)
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile:23:	docker-compose exec -T tools sh -c "USER_ID=`id --user` GROUP_ID=`id --group` make --directory=geoportal update-po"
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile:30:	docker-compose run --entrypoint= --no-deps --rm --volume=$(pwd)/geoportal:/app geoportal \
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile:35:	docker-compose run --entrypoint= --no-deps --rm --volume=$(pwd)/geoportal:/app geoportal \
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile:37:	docker-compose run --entrypoint= --no-deps --rm --volume=$(pwd)/geoportal:/app geoportal \
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile:42:	docker-compose -f docker-compose.yaml -f docker-compose-qgis.yaml run --rm qgis
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile:60:	docker-compose --file=docker-compose.yaml --file=docker-compose-db.yaml up -d db tools
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile:61:	docker-compose exec -T tools wait-db
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile:62:	docker-compose exec -T tools psql --command="DROP EXTENSION IF EXISTS postgis CASCADE"
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile:63:	scripts/db-restore --docker-compose-file=docker-compose.yaml --docker-compose-file=docker-compose-db.yaml \
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile:65:	docker-compose --file=docker-compose.yaml --file=docker-compose-db.yaml up -d
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile:69:	docker-compose exec -T tools pytest -vv tests/
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile:70:	ci/docker-compose-check
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/README.rst:27:   docker-compose up -d
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/build:133:        docker_compose_build_cmd = ["docker-compose", "build"]
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/build:138:                run(args, ["docker-compose", "pull", "--ignore-pull-failures"])  # nosec
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/build:162:                ["docker-compose", "ps", "--services", "--all"],
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/build:172:        run(args, ["docker-compose", "rm", "--force", "-v", "config"])
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/build:174:            run(args, ["docker-compose", "up", "--detach", "--force-recreate", service])
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/ci/docker-compose-check:14:        for s in subprocess.run(["docker-compose", "ps"], check=True, stdout=subprocess.PIPE)
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose-db.yaml:23:      file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose-qgis.yaml:8:      file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.override.sample.yaml:1:# This file can be renamed as `docker-compose.override.yaml` and uncomment the desired lines for
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.override.sample.yaml:2:# development. The file `docker-compose.override.yaml` is ignored by Git by default.
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.override.sample.yaml:33:  #     file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.override.sample.yaml:64:  #     file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:11:      file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:16:      file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:23:      file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:33:  ##     file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:44:      file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:52:      file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:58:  #     file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:63:  #     file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:70:  #     file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:77:      file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:84:      file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:91:      file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:100:      file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:105:      file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:113:      file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml:118:  #     file: docker-compose-lib.yaml
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/scripts/db-backup:92:                    "docker-compose",
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/scripts/db-restore:43:        "--docker-compose-file",
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/scripts/db-restore:46:        help="The docker-compose file to used.",
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/scripts/db-restore:95:                ["docker-compose"]
geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/.upgrade.yaml:19:    - docker-compose\.yaml
geoportal/c2cgeoportal_geoportal/scripts/manage_users.py:65:    Reset toto password to foobar: docker-compose
geoportal/c2cgeoportal_geoportal/scripts/manage_users.py:67:    admin: docker-compose exec geoportal manage-users --create --rolename=role_admin --password=bar foo.
geoportal/c2cgeoportal_geoportal/scripts/manage_users.py:69:    to get the options list, do: docker-compose exec geoportal manage-users --help
scripts/upgrade:59:    subprocess.call(["docker-compose", "down", "--remove-orphans"])
scripts/upgrade:61:        ["docker-compose", "pull", "--ignore-pull-failures"], env={**os.environ, "DOCKER_TAG": "unexisting"}
scripts/upgrade:63:    subprocess.check_call(["docker-compose", "up", "-d"])
scripts/upgrade:66:            "docker-compose",
```

**Comment by sbrunner** [comment]
@arnaud-morvan you don't looks to be on the right branch ...

**Review by arnaud-morvan — APPROVED** [review]
LGTM

**Pull request merged**
