### PR TITLE
Activate geometry_validation by default, Group layers config

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by asaunier** [comment]
Don't you need to add an entry in the changelog since the PR changes some config, doesn't it?

**Comment by sbrunner** [comment]
No because it's already included in the first point :
https://github.com/camptocamp/c2cgeoportal/blob/editing/c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl#L7-L26
:-)

**Comment by asaunier** [comment]
OK, no other objection.

**Comment by sbrunner** [comment]
Thanks :-)

**Pull request merged**
