### PR TITLE
Fix version conflict on some environment

### LINKED ISSUE #1238: FormAlchemy version conflict
```
mod_wsgi (pid=23678): Target WSGI script '/home/amorvan/aprona_websig/apache/application.wsgi' cannot be loaded as Python module.
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7] mod_wsgi (pid=23678): Exception occurred processing WSGI script '/home/amorvan/aprona_websig/apache/application.wsgi'.
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7] Traceback (most recent call last):
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/home/amorvan/aprona_websig/apache/application.wsgi", line 9, in <module>
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     application = get_app(configfile, 'main')
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/home/amorvan/aprona_websig/.build/venv/src/pyramid/pyramid/paster.py", line 31, in get_app
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     global_conf=options)
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/home/amorvan/aprona_websig/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     return loadobj(APP, uri, name=name, **kw)
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/home/amorvan/aprona_websig/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     global_conf=global_conf)
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/home/amorvan/aprona_websig/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     global_conf=global_conf)
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/home/amorvan/aprona_websig/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 320, in _loadconfig
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     return loader.get_context(object_type, name, global_conf)
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/home/amorvan/aprona_websig/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 450, in get_context
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     global_additions=global_additions)
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/home/amorvan/aprona_websig/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 559, in _pipeline_app_context
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     APP, pipeline[-1], global_conf)
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/home/amorvan/aprona_websig/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 454, in get_context
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     section)
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/home/amorvan/aprona_websig/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 476, in _context_from_use
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     object_type, name=use, global_conf=global_conf)
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/home/amorvan/aprona_websig/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 406, in get_context
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     global_conf=global_conf)
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/home/amorvan/aprona_websig/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     global_conf=global_conf)
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/home/amorvan/aprona_websig/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 328, in _loadegg
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     return loader.get_context(object_type, name, global_conf)
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/home/amorvan/aprona_websig/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 620, in get_context
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     object_type, name=name)
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/home/amorvan/aprona_websig/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 640, in find_egg_entry_point
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     pkg_resources.require(self.spec)
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     needed = self.resolve(parse_requirements(requirements))
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 588, in resolve
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7]     raise VersionConflict(dist,req) # XXX put more info here
[Tue Feb 17 15:33:17 2015] [error] [client 10.26.10.7] VersionConflict: (FormAlchemy 1.5.5 (/home/amorvan/aprona_websig/.build/venv/lib/python2.7/site-packages), Requirement.parse('FormAlchemy<=1.5'))

### PR DESCRIPTION
**Pull request by sbrunner**
fix #1238

### CODE REVIEW

**Comment by sbrunner** [comment]
Is this pull request ready ?

**Comment by asaunier** [comment]
> Is this pull request ready ?

Aren't you the author of the PR?

**Comment by sbrunner** [comment]
Ready to merge ...

**Comment by asaunier** [comment]
OK for me

**Pull request merged**
