### PR TITLE
Revert "Use the new version of tilecloud"

### PR DESCRIPTION
**Pull request by sbrunner**
This reverts commit 381ffeb3c8da55f9905fcf6a21e90159ceddc985.

### CODE REVIEW

**Comment by sbrunner** [comment]
Do not works with current version of tilecloud-chain ...

**Comment by rbovard** [comment]
ping @yjacolin

**Comment by sbrunner** [comment]
It will breaks the project update :-/

**Comment by rbovard** [comment]
And now all 2.x projects with tiles on SOS are broken...

**Comment by sbrunner** [comment]
You can do the update in the project...

**Pull request merged**
