### PR TITLE
Add javascript debug support in ngeo.html

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by fredj** [comment]
Thanks for any review

**Comment by elemoine** [comment]
What's the reason for closing this?

**Comment by fredj** [comment]
Apparently travis fails if the branch is not in camptocamp/c2cgeoportal (mine was in fredj/c2cgeoportal).

Faulty line: https://github.com/camptocamp/c2cgeoportal/blob/master/.travis.yml#L14

**Comment by elemoine** [comment]
That's a problem. It means we cannot receive contributions from people outside Camptocamp!

**Comment by sbrunner** [comment]
Effectively I will work on that!

**Pull request closed without merging**
