### PR TITLE
Replace jshint and gjslint with eslint

### LINKED ISSUE #2290: Use eslint instead of gjslint and jshint

### PR DESCRIPTION
**Pull request by fredj**
Fixes #2290

### CODE REVIEW

**Comment by sbrunner** [comment]
Looks good, merge when Travis is green :-)

**Comment by fredj** [comment]
@sbrunner is it correct that `+dot+eslintrc_tmpl` is in `c2cgeoportal/scaffolds/update/`?

**Comment by sbrunner** [comment]
Yes, for me that's looks good :-)

**Comment by fredj** [comment]
ok, thanks for the review

**Pull request merged**
