### PR TITLE
Backports from Luxembourg

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by asaunier** [comment]
What do you mean with "dbl"?
Concerning, 6cec33b shouldn't you be more explicit than "Backport from Luxembourg"?

**Comment by sbrunner** [comment]
double :-)

**Comment by sbrunner** [comment]
or better: duplicate

**Comment by sbrunner** [comment]
Update commit comment

**Comment by asaunier** [comment]
Get all the right versions without redundant cleanall

Please merge

**Pull request merged**
