### PR TITLE
Remove header from hop-by-hop transport

### PR DESCRIPTION
**Pull request by sbrunner**
@kalbermattenm does it will fix your issue #1394 ?

### CODE REVIEW

**Comment by kalbermattenm** [comment]
Not completely...

My header looks like that:
```
{
    'status': '200', 
    '<!-- error': 'It is not allowed to set both the GROUP and WMS_LAYER_GROUP for a layer -->, It is not
allowed to set both the GROUP and WMS_LAYER_GROUP for a layer -->, It is not allowed to set both the GROUP and WMS_LAYER
_GROUP for a layer -->, It is not allowed to set both the GROUP and WMS_LAYER_GROUP for a layer -->, It is not allowed t
o set both the GROUP and WMS_LAYER_GROUP for a layer -->, It is not allowed to set both the GROUP and WMS_LAYER_GROUP fo
r a layer -->, It is not allowed to set both the GROUP and WMS_LAYER_GROUP for a layer -->, It is not allowed to set bot
h the GROUP and WMS_LAYER_GROUP for a layer -->, It is not allowed to set both the GROUP and WMS_LAYER_GROUP for a layer
 -->, It is not allowed to set both the GROUP and WMS_LAYER_GROUP for a layer -->, It is not allowed to set both the GRO
UP and WMS_LAYER_GROUP for a layer -->, It is not allowed to set both the GROUP and WMS_LAYER_GROUP for a layer -->', 
    'keep-alive': 'timeout=5, max=100', 
    'server': 'Apache/2.2.29 (Win32) mod_fcgid/2.3.9 mod_wsgi/3.5 Python/2.7.8 mod_auth_sspi/1.0.4', 
    'connection': 'Keep-Alive',
    'date': 'Tue, 09 Jun 2015 06:00:28 GMT',
    'content-type': 'image/png'
}
```
To make it work, I had also to remove the `connection` header.

Both (`connection` and `keep-alive`) have to be removed for it to work:
```python
    if "keep-alive" in headers:  # pragma: no cover
        del headers["keep-alive"]  # no hop-by-hop transport
    if "connection" in headers:  # pragma: no cover
        del headers["connection"]  # no hop-by-hop transport
```

**Comment by sbrunner** [comment]
OK, thanks for your response :-)

**Comment by sbrunner** [comment]
Any review ?

**Comment by asaunier** [comment]
OK for me

**Pull request merged**
