### PR TITLE
Add templatecache.js.mako

### PR DESCRIPTION
**Pull request by fredj**
Same as #1439 but for with the changelog entry for version 2.0.0 (close #1439)

### CODE REVIEW

**Comment by asaunier** [comment]
Since templatecache.mako.js is a mako template generating a JS file, shouldn't it be named templatecache.js.mako instead?

**Comment by ochriste** [comment]
+1

**Comment by fredj** [comment]
+1, file renamed

**Comment by sbrunner** [comment]
Looks good :-)

**Comment by fredj** [comment]
don't merge yet, tests are broken

**Comment by sbrunner** [comment]
You should probably add `templatecache.js.mako` here: https://github.com/fredj/c2cgeoportal/blob/templatecache/c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl#L264-L267

**Comment by fredj** [comment]
Thanks @sbrunner ; it's working !

**Pull request merged**
