### PR TITLE
Fix typo and incorrect filename in CHANGELOG

### PR DESCRIPTION
**Pull request by asaunier**
By the way what are the "required changes" mentioned at point 2 of 1.6.3?

### CODE REVIEW

**Comment by sbrunner** [comment]
Many thanks, merge when Travis tests pass :-)

**Comment by asaunier** [comment]
What about the required changes to do in print/config.yaml.mako?

**Comment by sbrunner** [comment]
As I remember: changing the path because we moved the file

**Comment by asaunier** [comment]
Right:
```
<%include file="/A4_portrait.mako" />
```
should be transformed to
```
<%include file="templates/A4_portrait.mako" />
```
I think it is not explained in the changelog. I will add a line in the changelog.

**Comment by sbrunner** [comment]
+1

**Comment by asaunier** [comment]
> I will add a line in the changelog.

Done

**Comment by sbrunner** [comment]
Thanks :-)

**Pull request merged**
