### PR TITLE
Some upgrade improvement

### PR DESCRIPTION
**Pull request by sbrunner**
Already done by make
Template files can be useful to debug the build and the application
Add upgrade from 1.5 to 2.0 note

### CODE REVIEW

**Comment by asaunier** [comment]
Looks good to me

**Comment by elemoine** [comment]
See also my comments in https://github.com/camptocamp/c2cgeoportal/pull/1649.

**Comment by sbrunner** [comment]
Re: https://github.com/camptocamp/c2cgeoportal/pull/1649#discussion_r40572656

Tow reason of this:
 * Our current system don't support wheel than we need a new one.
 * The sysadmins frequently wanted to don't manage this server that can be replaced by a static repository.

Your right about the files size then do you have a better solution that respond on the tow previous points?

**Comment by elemoine** [comment]
Yesterday, @sbrunner and I briefly discussed the problems and potential solutions related to storing c2cgeoportal wheels in the repository's `gh-pages` branch. So we mentioned storing the wheels as GitHub releases instead, and using Travis' `releases` [provider](http://docs.travis-ci.com/user/deployment/releases/).

**Comment by sbrunner** [comment]
The pull request is updated to use the GitHub releases :-)

**Comment by asaunier** [comment]
Looks good to me

**Pull request merged**
