### PR TITLE
Add dependency to zip

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by fredj** [comment]
please merge when travis is green

**Comment by kalbermattenm** [comment]
This means that on Windows, the `zip` command has to exist, right ?

**Comment by sbrunner** [comment]
Yes and also unzip :-)
If i's difficult we can find a way to don't need them on windows...

**Comment by kalbermattenm** [comment]
Nope, should be possible (checked it, it is possible to install it through Cygwin)

I would just like to update the documentation (http://docs.camptocamp.net/c2cgeoportal/master/integrator/requirements.html#additional-notes-for-windows-users)...

Thanks for your answer.

**Pull request merged**
