### PR TITLE
Upgrade getitfixed (less intrusive on session)

### PR DESCRIPTION
**Pull request by arnaud-morvan**

### CODE REVIEW

**Comment by sbrunner** [comment]
explicit_manager stil be here: https://github.com/camptocamp/getitfixed/blob/master/getitfixed/models/__init__.py#L59
Custom dbsession_factory looks strange for me, why do you needs that?
https://github.com/camptocamp/getitfixed/blob/master/getitfixed/models/__init__.py#L65

**Comment by arnaud-morvan** [comment]
In getitfixed.includeme, I do not include getitfixed.models so this does not apply when getitfixed is used as a plugin (only in getitfixed.main or getitfixed.script.*).
Note that I do not know precisely why I need this, but it comes from the cookiecutter pyramid starter template and when I remove it completely, the tests suite fail.

**Comment by sbrunner** [comment]
OK, thanks :-)

**Comment by sbrunner** [comment]
Will be upgraded by: #5756

**Comment by sbrunner** [comment]
This should rebased to get the changes in the `geoportal/c2cgeoportal_geoportal/__init__.py` file.

**Comment by sbrunner** [comment]
Let's merge, the CI is OK :-)

**Pull request merged**
