### PR TITLE
Add print cancel, specify reqest method everywhere

### PR DESCRIPTION
**Pull request by sbrunner**
Related to https://github.com/Geoportail-Luxembourg/geoportailv3/issues/478

### CODE REVIEW

**Comment by asaunier** [comment]
What the link between GET request and printing cancellation?

**Comment by sbrunner** [comment]
Witch GET request ? the request method ?

**Comment by asaunier** [comment]
The one from
https://github.com/camptocamp/c2cgeoportal/commit/6e48432d743eb1b80ed62f571d92beb43d8304d9

**Comment by sbrunner** [comment]
Just that I see that when I add the print cancel :-)

**Comment by asaunier** [comment]
OK :)
Perhaps creating separated PR would have make more sense, but no big deal.

It looks good to me. Do you think adding ``request_method="GET"`` in project-specific routes are needed as well? If yes, shouldn't you add a note in the changelog?

**Comment by sbrunner** [comment]
No it's not a requirement it's just better :-)

**Pull request merged**
