### PR TITLE
Pdfreport improvements

### LINKED ISSUE #1236: Improvements needed in pdfreport tool
* ~~Doc (http://docs.camptocamp.net/c2cgeoportal/1.5/integrator/pdfreport.html) => add doc for missing .jar files (including postgresql JDBC driver). Unless they are added in MF Print v3? See https://github.com/camptocamp/schwyz_geoportal/commit/ac9db68e6367eaaf36ebc3f94e1681090c28beaf~~

* ~~If no map is embedded into the report, skip the WFS request URL generation https://github.com/camptocamp/c2cgeoportal/blob/1.5/c2cgeoportal/views/pdfreport.py#L91-L107 and do not complain if SRS is not set in the config~~

* ~~The "id" argument could also be a string, not only an integer: https://github.com/camptocamp/c2cgeoportal/blob/1.5/c2cgeoportal/__init__.py#L294~~

### PR DESCRIPTION
**Pull request by asaunier**
Fix #1236

### CODE REVIEW

**Comment by sbrunner** [comment]
Looks good, you can merge if Travis is happy :-)

**Comment by asaunier** [comment]
> Looks good, you can merge if Travis is happy :-)

Thanks, but I am preparing another commit for the second point of #1236

**Comment by asaunier** [comment]
PR is ready, please review :)

**Comment by sbrunner** [comment]
Looks good, just fix the case and merge :-)

**Pull request merged**
