### PR TITLE
Update mfp to 1e3fd91d53

### LINKED ISSUE #1492: Update print-servlet.war (Mapfish-print v3)
To get https://github.com/mapfish/mapfish-print/pull/282...

Thanks ;-)

### PR DESCRIPTION
**Pull request by tsauerwein**
To include PR https://github.com/mapfish/mapfish-print/pull/291 which automatically deletes old reports.

Closes  #1492

### CODE REVIEW

**Comment by sbrunner** [comment]
Looks good :-)

**Comment by kalbermattenm** [comment]
@tsauerwein, does this servlet also include https://github.com/mapfish/mapfish-print/pull/292 in order to fix https://github.com/camptocamp/c2cgeoportal/issues/1492 ?

**Comment by tsauerwein** [comment]
@kalbermattenm Yes, https://github.com/mapfish/mapfish-print/issues/292 is also included.

**Comment by kalbermattenm** [comment]
Cool, thanks a lot !

**Comment by tsauerwein** [comment]
Travis passed, merging.

**Pull request merged**
