### PR TITLE
Update the projects to make

### PR DESCRIPTION
**Pull request by sbrunner**
The modification of the CONST_CHANGELOG  will be done in a separate pull request :-)

### CODE REVIEW

**Comment by sbrunner** [comment]
Now this pull request is ready, please review :-)

**Comment by asaunier** [comment]
Looks good to me, but it's hard to make a precise review because of the huge amount of changes.
Just one question: the changelog for GMF 1.6 is surprisingly small. Shouldn't you add notes explaining how the buildout config (for instance db info) must be migrated to make?

**Comment by sbrunner** [comment]
@asaunier yes, this will be in the CONST_CHANGELOG :-)

**Comment by asaunier** [comment]
No objection then.

**Pull request merged**
