### PR TITLE
Send MapServer substitution only on MapServer with standard auth

### PR DESCRIPTION
**Pull request by sbrunner**
Fix some typo

Related to GEO-4467

### CODE REVIEW

**Comment by ochriste** [comment]
@sbrunner whats the idea here? we can only use mapserver substitution with standart auth? does that mean nyon use non standart auth? or is the issue elsewhere?

**Comment by sbrunner** [comment]
They use a no auth with arcgis, and they have an issue because the URL is too long for unneeded parameters...

**Comment by ochriste** [comment]
@sbrunner  so the issue is that with arcgis server, there is an url length limitation that make authentication impossible because adding extra parameter to pass the auth info make the whole url too long?
shouldnt we document this kind of things somewhere?

**Comment by ochriste** [comment]
@sbrunner what about qgis-server backend? it doesnt support authentication either?

**Comment by sbrunner** [comment]
QGIS server access control plugin currently didn't support MapServer substitution :-P 
At therm, he should support column filtering but throw another way...

**Comment by ochriste** [comment]
@sbrunner ok thank you

**Pull request merged**
