### PR TITLE
Change fts to keep some characters

### PR DESCRIPTION
**Pull request by gberaudo**
`-*'` should be kept as-is.

### CODE REVIEW

**Comment by sbrunner** [comment]
Can you update those tow lines of doc: https://github.com/camptocamp/c2cgeoportal/blob/b9de1ab58cee4ce9a8bfc37819ee469082abc18d/doc/integrator/fulltext_search.rst.mako#L69
https://github.com/camptocamp/c2cgeoportal/blob/b9de1ab58cee4ce9a8bfc37819ee469082abc18d/doc/integrator/fulltext_search.rst.mako#L83

**Comment by gberaudo** [comment]
Done

**Comment by gberaudo** [comment]
Thanks, @sbrunner could you create a new tag?

**Comment by sbrunner** [comment]
Thanks :-), yes ;-)

**Comment by sbrunner** [comment]
https://pypi.python.org/pypi/c2cgeoportal/ :-)

**Pull request merged**
