### PR TITLE
Remove groups when all child layers have been stripped out of getcap

### PR DESCRIPTION
**Pull request by asaunier**
As for now, the filter_capabilities tool removes not allowed layers from the WMS getcapabilities response. On the other hand if the removed layers are contained in a mapserver group, the group remains even though no embedded layers are shown.

This PR makes sure the group is removed as well if all contained layers have been removed.

Most of the code is from @sbrunner

### CODE REVIEW

**Comment by sbrunner** [comment]
Looks good but the tests should be updated

**Comment by asaunier** [comment]
It seems that the changes broke the WFS filtering. Commit 0a22be3 should fix this.

For the tests I am going to add the case of a group with only private layers.

**Comment by asaunier** [comment]
Commits have been merged/rebased, tests added and pass. The changes have been tested for real with BL's GeoWMS.

**Comment by sbrunner** [comment]
Looks good for me, merge :-)

**Comment by asaunier** [comment]
OK merging.
Thanks @sbrunner for reviewing and your help to write the code.

**Pull request merged**
