### PR TITLE
Better upgrade final message

### PR DESCRIPTION
**Pull request by rbovard**

### CODE REVIEW

**Comment by rbovard** [comment]
@sbrunner I tried to rebase onto 2.1 with `git rebase --interactive origin/2.1` but I have this error:

```
fatal: Needed a single revision
invalid upstream origin/2.1
```

Any idea to fix that? I think it's because the `2.1` branch doesn't exist in my fork.

**Comment by sbrunner** [comment]
Witch remotes do you have?
`git remote -v`

**Comment by rbovard** [comment]
```
camptocamp      https://github.com/camptocamp/c2cgeoportal.git (fetch)
camptocamp      https://github.com/camptocamp/c2cgeoportal.git (push)
origin  https://github.com/rbovard/c2cgeoportal.git (fetch)
origin  https://github.com/rbovard/c2cgeoportal.git (push)
upstream        https://github.com/camptocamp/c2cgeoportal.git (fetch)
upstream        https://github.com/camptocamp/c2cgeoportal.git (push)
```

**Comment by sbrunner** [comment]
Then do:
```bash
git fetch upstream
git rebase --interactive upstream/2.1
```
:-)

**Comment by rbovard** [comment]
Seem so simple, thanks!

Please review.

**Pull request merged**
