### PR TITLE
Remove sencha touch and print v2 support

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by fredj** [comment]
you can remove more code in `c2cgeoportal/__init__.py` and in the doc

**Comment by sbrunner** [comment]
Effectively, thanks :-)

**Comment by fredj** [comment]
And the `INTERFACE_TYPE_SENCHA_TOUCH` related code in `c2cgeoportal/__init__.py`

**Comment by sbrunner** [comment]
Thanks again :-)

**Comment by fredj** [comment]
LGTM, thanks !

**Pull request merged**
