### PR TITLE
Deploy on GitHub releases

### PR DESCRIPTION
**Pull request by sbrunner**
On each commit on master and x.y branches a new wheel will be added on a GitHub release.

### CODE REVIEW

**Comment by asaunier** [comment]
No objection

**Comment by elemoine** [comment]
I see duplications in the wheel name on github.io. See http://camptocamp.github.io/c2cgeoportal/index/c2cgeoportal/index.html. Is this expected?

**Comment by sbrunner** [comment]
No but it's done by an old version the last one shouldn't do that :-)

**Comment by elemoine** [comment]
Ok thanks.

So with this new approach we create one tag/release per push to the master branch on GitHub. We will soon end up with tons of tags/releases. I was hoping that when pushing to the master branch on GitHub we would new wheels to a specific "dev" release or something. But maybe that's not possible.

**Comment by sbrunner** [comment]
Yes but for that we should create an arbitrary tag and the sources download will give something not related to the release :-(

**Pull request merged**
