### PR TITLE
Rebuild the mako when we modify the vars

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by asaunier** [comment]
Isn't it already the case since
```
VARS_DEPENDS += $(VARS_FILES) .build/node_modules.timestamp
```
https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl#L283

**Comment by sbrunner** [comment]
You point the project CONST_Makefile but I modify the c2cgeoportal Makefile :-)

**Comment by asaunier** [comment]
OK then

**Comment by sbrunner** [comment]
Thanks :-)

**Pull request merged**
