### PR TITLE
Best place for b flag in git submodule add command

### PR DESCRIPTION
**Pull request by yjacolin**
git submodule add -b <version> <repository> <path> is working.

### CODE REVIEW

**Comment by sbrunner** [comment]
It don't do the same, what you purpose add the branch in the .gitmodules, and the c2ctool suppose that's not the case ...

**Comment by yjacolin** [comment]
@sbrunner what the original commande line is suppose to do?

I thought that my CGXP submodules will be on 1.6 branch which is not.

**Comment by sbrunner** [comment]
effectively there is something wrong, but i don't like this reference of the original branch in the `.gitmodules` it can be confusing...
then I prefer:
```
git submodule add git@github.com:camptocamp/cgxp.git <project>/<package>/static/lib/cgxp
git submodules foreach git checkout <version>
```

**Comment by sbrunner** [comment]
Thanks that's looks good, merge when Travis tests pass :-)

**Pull request merged**
