### PR TITLE
Cleanup admin interface config

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by asaunier** [comment]
What if you have other available functionalities than the 3 types mentioned? You must keep the config as is?

**Comment by sbrunner** [comment]
Yes :-)

**Comment by asaunier** [comment]
So perhaps you should be a little clearer and say that those are the default settings and that it is no use overridding them unless a custom config is required?

**Comment by sbrunner** [comment]
Updated :-)

**Comment by asaunier** [comment]
Thanks, please merge.

**Pull request merged**
