### PR TITLE
Add optional reissue_time config value

### LINKED ISSUE #1843: Cookie expiration date
Is there a way to use `authtkt timeout` value since last load of the page and not since the last login?

For example on github.com, the cookie `user_session` has an expiration date of now + 2 weeks, if I reload the page, the expiration date is updated.

### PR DESCRIPTION
**Pull request by sbrunner**
fix #1843

### CODE REVIEW

**Comment by ger-benjamin** [comment]
LRTM

**Comment by sbrunner** [comment]
Thanks :-)

**Comment by asaunier** [comment]
LRTM?

**Comment by sbrunner** [comment]
LGTM?

**Comment by ger-benjamin** [comment]
(Typo...)

**Pull request merged**
