### PR TITLE
Fix dynamic for API

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Review by arnaud-morvan — COMMENTED** [review]
I do not really understand what you fix here.
Is there something that really change ?

**Comment by sbrunner** [comment]
With the old code we try to get the route named api for the api who doesn't exists, see: 
https://sentry.io/organizations/camptocamp/issues/2057061059/?project=1851011&query=&statsPeriod=14d

**Comment by arnaud-morvan** [comment]
Yes, but I do not understand what changed, you still call request.route_url with interface_name.

**Comment by sbrunner** [comment]
Yes for the standard interface (desktop, mobile, iframe_api), but not for the api (JavaScript)...

**Review by arnaud-morvan — APPROVED** [review]
Sorry, api does not extends defaults. Looks good.

**Pull request merged**
