### PR TITLE
Convert METADATA wms_srs to uppercase

### PR DESCRIPTION
**Pull request by arnaud-morvan**
Change "wms_srs" "epsg:..." to "wms_srs" "EPSG:..." in c2cgeoportal.map.mako.
Tell to do the same in all mapfiles in the changelog.

### CODE REVIEW

**Comment by asaunier** [comment]
Looks good. But maybe you should explain in the changelog why epsg code must be uppercased?

**Comment by arnaud-morvan** [comment]
I've seached the web, but not found real explanation.
It is wrote uppercase everywhere (in mapserver documentation, WMS specification) but it is not explained or clearly specified.
I've added link to http://www.mapserver.org/ogc/wms_server.html#setup-a-mapfile-for-your-wms

**Comment by asaunier** [comment]
I don't really see any explanations or advices about the case of EPSG codes in that page :P 
I would rather write that using lowercase codes may cause incompatibility problems with some client tools including WMSBrowser.

**Comment by arnaud-morvan** [comment]
I've pasted your explanation in the changelog.
Thanks for review.

**Comment by asaunier** [comment]
Thanks for the changes. Looks good to me!

**Comment by sbrunner** [comment]
For me also :-)

**Pull request merged**
