### PR TITLE
One printserver in a set of site

### PR DESCRIPTION
**Pull request by ger-benjamin**

### CODE REVIEW

**Comment by sbrunner** [comment]
Can you add a notes in the documentation to indicates that works for the version 2 and it should be adapted for the version 3 ?

**Comment by ger-benjamin** [comment]
Somethings like that ? :
````
+
+.. note::
+
+   This system works for print v2 but must be adapted for
+   print v3 (although that's the same idea).
````

**Comment by sbrunner** [comment]
yes :-)

**Comment by ger-benjamin** [comment]
Thanks @sbrunner

**Pull request merged**
