### PR TITLE
Disable GET login

### PR DESCRIPTION
**Pull request by sbrunner**
If you need it do it in the project!

### CODE REVIEW

**Comment by ochriste** [comment]
mmm, didnt we need that for epfl ?

**Comment by ochriste** [comment]
see https://github.com/camptocamp/c2cgeoportal/commit/d26f1dbc95cb2cbdcef88f21437a62c0ea47477c

**Comment by sbrunner** [comment]
=> If you need it do it in the project!

d26f1db make that we are able to do awful things, like login in get :-(

**Comment by ochriste** [comment]
well you will have to show me how to override that

**Comment by sbrunner** [comment]
Just add in the project:
`config.add_route("login", "/login", request_method="GET")`
:-)

**Comment by ochriste** [comment]
thx!

**Pull request merged**
