### PR TITLE
Fix referrer check with query string

### LINKED ISSUE #3676: Referer check don't works on non flush mode on dev instance
authorised referer: https://schwyz-geoportal-new-stretch.dev.sig.cloud.camptocamp.net/wkaltz/
used referer: https://schwyz-geoportal-new-stretch.dev.sig.cloud.camptocamp.net/wkaltz?lang=de&baselayer_ref=ch.swisstopo.pixelkarte-grau

Should be considered as valid but it's not...

### PR DESCRIPTION
**Pull request by sbrunner**
fix #3676

### CODE REVIEW

**Comment by jwkaltz** [comment]
@sbrunner I am going to try out the fix on SZ dev environment

**Comment by sbrunner** [comment]
+1 @jwkaltz

**Comment by jwkaltz** [comment]
I tested the changes by keeping standard authorized_referers on https://schwyz-geoportal-new-stretch.dev.sig.cloud.camptocamp.net/wkaltz-test
authorized_referers: ['https://schwyz-geoportal-new-stretch.dev.sig.cloud.camptocamp.net/wkaltz-test/']

Before changes: Login/Logout NOK
After changes: Login/Logout OK

So fix is working.

**Comment by sbrunner** [comment]
Thanks :-)

**Pull request merged**
