### PR TITLE
Some changes arround c2ctool

### LINKED ISSUE #1180: in c2ctool the submodules should be updated after each git update
```
check_call(['git', 'submodule', 'foreach', 'git', 'submodule', 'sync'])
check_call(['git', 'submodule', 'foreach', 'git', 'submodule', 'update', '--init'])
```

### PR DESCRIPTION
**Pull request by sbrunner**
fix #1180

### CODE REVIEW

**Comment by sbrunner** [comment]
fix #1235

**Comment by asaunier** [comment]
> fix #1235

The comment above references the PR itself. I guess the issue id is wrong.

**Comment by sbrunner** [comment]
.. :-/ I don't remember witch one ...

**Comment by sbrunner** [comment]
Comment updated with the right issue :-)

**Pull request merged**
