### PR TITLE
Upgrade Pyramid to version 2.0

### PR DESCRIPTION
**Pull request by arnaud-morvan**

### CODE REVIEW

**Comment by sbrunner** [comment]
c2cgeoform and getitfixed are automatically updated, but not pyramid... should we update this pull request?

**Review by sbrunner — APPROVED** [review]
In the `geoportal/c2cgeoportal_geoportal/scripts/pcreate.py` file it seals have some commented code
I trust you on the details :-)

**Comment by arnaud-morvan** [comment]
@sbrunner : I still have errors during checks, probably due to "_tmpl" suffix that have been removed in scaffolds.
I already fixed some.
I did not managed to reproduce everything locally.
You help would be welcome now.

**Comment by sbrunner** [comment]
OK, I will have a look :-)

**Comment by arnaud-morvan** [comment]
@sbrunner : be careful, I just added a commit here with missing print config file.

**Comment by sbrunner** [comment]
Should probably be updated:
https://github.com/camptocamp/c2cgeoportal/blob/GSGMF-1565-pyramid2/Dockerfile#L138-L144
https://github.com/camptocamp/c2cgeoportal/blob/GSGMF-1565-pyramid2/build.mk

**Comment by arnaud-morvan** [comment]
@sbrunner : I did not managed to fix build.mk
```
+ make --makefile=build.mk build
make: *** No rule to make target 'geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_create_template/', needed by 'build'.  Stop.
```

**Comment by sbrunner** [comment]
Isn't that wrong?
https://github.com/camptocamp/c2cgeoportal/blob/0aa1416f820681fb4a343485b8ee01ff6cdcbb55/build.mk#L128-L138

**Comment by sbrunner** [comment]
This should be updated :-)
https://github.com/camptocamp/c2cgeoportal/blob/GSGMF-1565-pyramid2/.gitattributes#L4

**Comment by sbrunner** [comment]
@arnaud-morvan I combine all my fix in one commit, for me, it is ready to be merged (except swashing commits :-) )

**Pull request merged**
