### PR TITLE
Use the released version of bootstrap-table

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
Looks good, needs to be tested in browser.
I suppose opencollective could be removed.

**Comment by sbrunner** [comment]
Tested here: https://geomapfish-demo.camptocamp.com/sbrunner23/
Looks to work well :-)

**Comment by arnaud-morvan** [comment]
Also note that we may use the minified version now in admin/c2cgeoportal_admin/templates/index.jinja2

**Comment by arnaud-morvan** [comment]
I was using the non minified version because the repository minified version seems to be updated update on release tag only.

**Pull request merged**
