### PR TITLE
Fix fields rename in admin interface

### LINKED ISSUE #1785: administration interface: legend rule is not editable
In the *layer*-section in the administration interface it is not possible any more to set or edit *legend rule*.

(from https://github.com/camptocamp/baselstadt_mapbs/issues/65)

### PR DESCRIPTION
**Pull request by sbrunner**
fix #1785

### CODE REVIEW

**Comment by asaunier** [comment]
Looks good

**Comment by tsauerwein** [comment]
Did this also fix https://github.com/camptocamp/c2cgeoportal/issues/1785?

**Comment by sbrunner** [comment]
As the initial comment say ... yes :-)

**Comment by sbrunner** [comment]
I just close it also :-)

**Pull request merged**
