### PR TITLE
Get wfs types though mapservproxy

### PR DESCRIPTION
**Pull request by arnaud-morvan**
Using this we could show in cgxp_querier only the layers the user have access to : 
```
featureTypes: ${dumps(list(set(loads(WFSTypes))&set(['locaux','cameras']))) | n},
```

### CODE REVIEW

**Comment by sbrunner** [comment]
To solve that you should use functionalities as it explained here: http://docs.camptocamp.net/c2cgeoportal/1.6/integrator/functionality.html#using-functionalities-list-to-configure-the-layers-in-the-querybuilder

**Comment by arnaud-morvan** [comment]
Functionnalities do not seems very useful for this. I don't see any reason to not use proxy filtering on wfs_types since role_id is taken in cache key.

**Comment by sbrunner** [comment]
- Using cache on the results
- One less query

**Comment by arnaud-morvan** [comment]
Cache is made on a role basis, so this is not a problem.
I prefer to get one more request than having to keep two different system for layer rights.

**Comment by arnaud-morvan** [comment]
I close the pull request since ``functionnalities`` make the job, but I do not understand why we do not use proxy filtering here.

**Comment by arnaud-morvan** [comment]
@sbrunner 
Since wfs_types are caches on a role basis, we get only one request per role, this really do not make sense to not use proxy filtering. I really do not agree with you on this.

**Comment by sbrunner** [comment]
I don't completely desaggree with that, but
- I don't want to have regression on the branch 1.6 than it should be done on 2.0 or master
- To make the cache working you should add a role_id argument to the methode `_wfs_types_cached`
- You should remove all this block: https://github.com/camptocamp/c2cgeoportal/blob/bb848556e9b7d0ee5d7bec1a4f8f46cefd6fc2fb/c2cgeoportal/views/entry.py#L713-L722
- Have one less method (`_wfs_types` became just a pass throw)
- Do the same for `_external_wfs_types`

**Pull request closed without merging**
