### PR TITLE
Allows nearly all variable to be from environment variable

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Review by arnaud-morvan — APPROVED** [review]
I do not see any better solution to allow using env vars here.
So +1

**Comment by arnaud-morvan** [comment]
Be careful that some variables may not be correctly parsed (typed) at runtime.

**Comment by sbrunner** [comment]
@arnaud-morvan effectively if you do that you should do something like:
 ```
 runtime_postprocess:
  - expression: int({})
    vars:
       - ...
```
or
 ```
 runtime_postprocess:
  - expression: {}.lower() in ('true', 'yes', '1')
    vars:
       - ...
```
I see that some vars are already in, do you think that I should add the others?

**Comment by arnaud-morvan** [comment]
Not sure, but I won't have found how to handle this myself, so it suppose it is the same for everyone except you.

**Pull request merged**
