### PR TITLE
Fix the main_version, convert array to string

### PR DESCRIPTION
**Pull request by ochriste**

### CODE REVIEW

**Comment by sbrunner** [comment]
Should be rebased :-)

**Comment by ochriste** [comment]
rebase 2.0 sur master ? seems confusing.
I think I will let you fix this

**Comment by sbrunner** [comment]
2.0, a pullrequest that fix Travis just be merged :-)

**Comment by ochriste** [comment]
ok

**Comment by sbrunner** [comment]
Thanks, Looks good, merge ;-)

**Pull request merged**
