### PR TITLE
Update to documentation used to run the tests

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by sbrunner** [comment]
On witch command?

**Comment by sbrunner** [comment]
What's your docker and docker compose versions?

**Comment by julsbreakdown** [comment]
The versions on the server 
Docker => 1.10.3 
docker-compose : 1.8.1

**Comment by sbrunner** [comment]
It don't works on the gmf-test.sig.cloud.camptocamp.net !

**Comment by julsbreakdown** [comment]
Ok so how do I test it. Must I build the whole thing on my local machine. And whats is the point of having the server then =(

**Comment by sbrunner** [comment]
> Must I build the whole thing on my local machine.

Yes

> And whats is the point of having the server then

The server is to build the demo application <= 2.2.x :-)

The infra for the 2.3 isn't yet ready :-)

**Pull request merged**
