### PR TITLE
Add doc about CONFIG_VARS

### PR DESCRIPTION
**Pull request by asaunier**
CONFIG_VARS is already described here http://docs.camptocamp.net/c2cgeoportal/1.6/integrator/make.html#makefile-config-variables but I think we could make it even more obvious, because making config vars available in the templates or python code is a recurrent question.

### CODE REVIEW

**Comment by rbovard** [comment]
+1 :)

**Comment by asaunier** [comment]
@rbovard I read your question at https://github.com/camptocamp/c2cgeoportal/issues/1791 :)
Actually I had the same problem a few weeks ago and though that the doc was not clear enough about that point. I hope this PR will help.

**Comment by sbrunner** [comment]
Excellent, thanks @asaunier

**Comment by sbrunner** [comment]
Excellent, thanks @asaunier

**Comment by kalbermattenm** [comment]
Thanks @asaunier, I thought about adding some doc, but I was too lazy... (bad me...)

**Pull request merged**
