### PR TITLE
Set url for Closure Linter

### PR DESCRIPTION
**Pull request by ger-benjamin**
Should fix: https://github.com/camptocamp/c2cgeoportal/issues/2472

(Merge on 2.0)

### CODE REVIEW

**Comment by ger-benjamin** [comment]
I don't understand the travis issue

**Comment by sbrunner** [comment]
And this time you should backport: https://github.com/camptocamp/c2cgeoportal/commit/4d56b660c867a9f6254186f064f941ad02a12501 ...

**Comment by sbrunner** [comment]
Looks good, merge :-)

**Comment by ger-benjamin** [comment]
Thanks @sbrunner

**Pull request merged**
