### PR TITLE
added missing pyramid_closure include

### PR DESCRIPTION
**Pull request by ochriste**

### CODE REVIEW

**Comment by ochriste** [comment]
test fail because of a problem in pyramid_closure where the view is defined before the route and somehow the tests dont like that anymore.
waiting on pyramid_closure fix

**Comment by elemoine** [comment]
See https://github.com/camptocamp/pyramid_closure/pull/56.

**Comment by elemoine** [comment]
I'd just add a note to the changelog to indicate that `config.include('pyramid_closure')` can be removed from the application's main function as this is now done by c2cgeoportal.

Otherwise looks good to me.

**Comment by ochriste** [comment]
done

**Comment by elemoine** [comment]
Thanks for adding a note to the changelog. Please merge when Travis is happy.

**Pull request merged**
