### PR TITLE
Update OpenLayers to 2.13.1

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by asaunier** [comment]
OpenLayers 2.12 or 2.13?

**Comment by sbrunner** [comment]
Oups 2.13 ...

**Comment by asaunier** [comment]
Looks good to me :)

**Comment by fredj** [comment]
but the commit (in `c2cgeoportal/static/lib/openlayers`) is the 2.12 version: https://github.com/openlayers/openlayers/commit/0412410be0ec43dc9a5c258b640a793fad41bd88

**Comment by sbrunner** [comment]
Thanks @fredj :-)

**Pull request merged**
