### PR TITLE
Unicode string before encoding it

### LINKED ISSUE #2717: Encoding problem with translation script
Version 2.1.0.dev25 
```
.build/venv/bin/l10nv1tov2 fr cartoriviera/static/js/Proj/Lang/fr.js cartoriviera/locale/fr/LC_MESSAGES/cartoriviera-client.po
Traceback (most recent call last):
  File ".build/venv/bin/l10nv1tov2", line 11, in <module>
    sys.exit(main())
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish_v2/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/l10nv1tov2.py", line 96, in main
    """.format(key, value.replace('"', '\\"'))).encode("utf-8"),
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 25: ordinal not in range(128)
```
Something wrong in my base file ?

### PR DESCRIPTION
**Pull request by ger-benjamin**
Fix #2717

@sbrunner I'm 100% sure, with this, the wrote string will be `thème` and not `th\xc3\xa8me` ? right ?

### CODE REVIEW

**Comment by sbrunner** [comment]
I change the base than I get many unwanted commits...

**Comment by ger-benjamin** [comment]
Thanks sbrunner. I've "rebased" on 2.1

**Comment by sbrunner** [comment]
The parent commit is 20 days old :-(, is should be re-based on last commit ...

**Comment by ger-benjamin** [comment]
I wait on https://github.com/camptocamp/c2cgeoportal/pull/2727

**Comment by ger-benjamin** [comment]
I wait on https://github.com/camptocamp/c2cgeoportal/pull/2727

**Pull request merged**
